travel = ["beijing","shanghai","america","japan","italy"]
print(travel)
#print(sorted(travel))
#print(travel)
#print(sorted(travel,reverse=True))
#print(travel)
travel.reverse()
print(travel)
travel.reverse()
print(travel)
travel.sort()
print(travel)
travel.sort(reverse=True)
print(travel)
print(len(travel))
for place in travel:
    print(place)
